---
- name: Configure IS-IS Simple 4n Lab
  hosts: clab_isis_s4n
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ inventory_hostname }}"
      password: admin
      username: admin

  roles:
    - mikrotik-routeros-common
    - mikrotik-routeros-ip-address
    - mikrotik-routeros-routing-isis
